[Interface]
Address = 10.13.13.2
PrivateKey = yBnJsY4Wi+qkcAThxwNEhwp8Xf1QmGpliRw2GkurZnM=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = y/2oNYkr3NM/K+n0dvItBWk41YKLzZlT21b2HvVEZj4=
PresharedKey = 0cHWcRuCMGH6x+CDN2u2bdIOuYeq+2ZH2dq8ARgwv1o=
Endpoint = club.dansonlinepresence.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
